export const PROFILE = {
  name: 'Ahmad Rashad Mojeeb',
  tagline: 'Full Stack & Generative AI developer',
  email: 'mojeebahmadrashad@gmail.com',
  phone: '0348-5416025',
  github: 'https://github.com/ahmadrashad1',
  githubRepos: 'https://github.com/ahmadrashad1?tab=repositories',
  linkedin: 'https://linkedin.com/in/ahmad-rashad-mojeeb',
  about: `Computer Science student at FAST NUCES with strong knowledge of Generative AI architectures including neural networks, transformers, retrieval-augmented generation (RAG), diffusion models, and multimodal systems. Solid foundation in operating systems, algorithms, data structures, and web security. Experienced in building full-stack applications using React and Spring Boot REST APIs, Dockerized deployments, SQL databases, and Agile (Scrum) methodologies.`,
  expertise: [
    'Full-stack (React, Spring Boot, MERN, Node.js)',
    'Generative AI: Transformers, RAG, Diffusion Models, GANs',
    'Automation: n8n workflows, LangChain orchestration, agent pipelines',
    'RAG systems: ingestion, chunking, embeddings, retrieval, evaluation',
    'Languages: Python, Java, C++, JavaScript, C#, SQL',
    'Databases: MySQL, MongoDB, Firebase',
    'Tools: Docker, Git, Postman, JUnit5, Jira',
    'Agile, Scrum, API testing',
  ],
}

export const WORK = [
  {
    title: 'SAFAYIPAK',
    subtitle: 'MERN Stack · Auth & CRUD',
    slug: 'safayipak',
    gradient: 'linear-gradient(135deg, #0f766e 0%, #134e4a 50%, #0a0a0a 100%)',
    accent: '#14b8a6',
    tags: ['MongoDB', 'Express', 'React', 'Node'],
  },
  {
    title: 'SportSync',
    subtitle: 'Sports Event Management',
    slug: 'sportsync',
    gradient: 'linear-gradient(135deg, #1e40af 0%, #1e3a8a 50%, #0a0a0a 100%)',
    accent: '#3b82f6',
    tags: ['Spring Boot', 'React', 'MySQL', 'Agile'],
  },
  {
    title: 'Vehicle Tracking System',
    subtitle: 'Real-time tracking · REST API',
    slug: 'vehicle-tracking',
    gradient: 'linear-gradient(135deg, #b45309 0%, #92400e 50%, #0a0a0a 100%)',
    accent: '#f59e0b',
    tags: ['React', 'Spring Boot', 'Docker', 'WebSockets'],
  },
  {
    title: 'Text-to-Icon Generator',
    subtitle: 'Diffusion Models · DreamBooth, LoRA',
    slug: 'dreamicon',
    gradient: 'linear-gradient(135deg, #7c3aed 0%, #5b21b6 50%, #0a0a0a 100%)',
    accent: '#a78bfa',
    tags: ['Diffusion', 'LoRA', 'DreamBooth', 'Python'],
  },
  {
    title: 'Multimodal RAG',
    subtitle: 'Document Intelligence · Vision + Language',
    slug: 'multimodal-rag',
    gradient: 'linear-gradient(135deg, #be185d 0%, #9d174d 50%, #0a0a0a 100%)',
    accent: '#ec4899',
    tags: ['Transformers', 'RAG', 'Vision', 'LLM'],
  },
  {
    title: 'Academic & Research',
    subtitle: 'CycleGAN, DiT, CNN, TORCS, C++',
    slug: 'academic',
    gradient: 'linear-gradient(135deg, #374151 0%, #1f2937 50%, #0a0a0a 100%)',
    accent: '#9ca3af',
    tags: ['ML', 'C++', 'Research', 'Algorithms'],
  },
]

export const MARQUEE_TAGS = [
  'full-stack',
  'generative AI',
  'web apps',
  'databases',
  'open source',
  'React',
  'Spring Boot',
  'Python',
  'Java',
  'machine learning',
]
